title: House of Zamods
description: All in one website for zamods activity, blog, portfolio, products, offering & links 
baseurl: "/site" # the subpath of your site, e.g. /blog
url: "https://zamods.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author information
author:
  name: Zamods
  email: zamods@altmails.com
  bio: Just a dude with a broom and balls.
  description: Dream is dream just like cream is cream but cream can be ice cream, milk cream, whip cream but only dream is absolute.

# Social media links
social:
  github: Zamods
  linkedin: ssiawa
  instagram: sdomaz

# Theme settings
theme_settings:
  dark_mode: true
  search: true
  newsletter: false
  comments: false
  google_analytics: true

# Google Analytics
google_analytics: G-RZW6LCL2B1

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Pages Path
defaults:
  - scope:
      path: "_pages"
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: assets/scss
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.text
  - README.md
  - SECURITY.md
